Rails.application.config.assets.precompile += %w( polls_util.js )
Rails.application.config.assets.precompile += %w( articles_util.js )
#Rails.application.config.assets.precompile += %w( elections_util.js )
Rails.application.config.assets.precompile += %w( home_util.js )
Rails.application.config.assets.precompile += %w( header.css )
Rails.application.config.assets.precompile += %w( footer.css )
Rails.application.config.assets.precompile += %w( home.css )