# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bfd47cf0f89d8ddd88d5998f559fa457805d9bfd9d66c4385b4c1939d1e3f0d61b0c095a3414a50480f67000bc796b078842facddf59804a5befadf2d2e854

test:
  secret_key_base: 258f60f5594a53170e3d72fab32cd8b1b181fcece091849d0afe7082e7382fdb06b070f6212c4878ea3e87c7f96148710e7271f5e239c96a275ad55c0878f08e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
